# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0002_auto_20171203_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
