# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0003_auto_20171203_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='burgershop.Order', verbose_name='Заказ'),
        ),
    ]
