# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0004_auto_20171204_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='burgershop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='burgershop.BurgerShop', verbose_name='Место работы'),
        ),
    ]
