# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0005_user_burgershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 13, 19, 29, 279106), verbose_name='Время создания'),
        ),
    ]
