# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0006_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
    ]
