# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0007_auto_20171204_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания'),
        ),
    ]
